# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0002_sitequeuemanager_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanager',
            name='queue_group_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
