# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-11 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0003_sitequeuemanager_queue_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanager',
            name='browser_agent',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
